version: "3.9"
services:
  static:
    build:
      context: docker
      dockerfile: production/nginx/Dockerfile
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.svodd-static.rule=Host(`static.localhost`)
      - traefik.http.routers.svodd-static.entryPoints=http
      - traefik.http.services.svodd-static.loadBalancer.server.port=80

networks:
  traefik-public:
    name: traefik-public
    external: true
