version: "3.9"
services:
  static:
    image: ${REGISTRY}/svodd-static:${IMAGE_TAG}
    networks:
      - traefik-public
      - default
    deploy:
      placement:
        constraints: [ node.role == manager ]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.svodd-static.rule=Host(`static.svodd.ru`)
        - traefik.http.services.svodd-static.loadBalancer.server.port=80
        - traefik.http.routers.svodd-static.middlewares=secure-headers
        - traefik.http.routers.svodd-static.entryPoints=https
        - traefik.http.routers.svodd-static.tls=true
        - traefik.http.routers.svodd-static.tls.certResolver=letsEncrypt

networks:
  traefik-public:
    name: traefik-public
    external: true
