version: "3.9"
services:
  static:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.svodd-static.rule=Host(`static.localhost`)
      - traefik.http.routers.svodd-static.entryPoints=http
      - traefik.http.services.svodd-static.loadBalancer.server.port=80
      - traefik.http.middlewares.svodd-static-redirect.redirectRegex.regex=^(https?://)static.localhost/(.*)$$
      - traefik.http.middlewares.svodd-static-redirect.redirectRegex.replacement=$${1}static.localhost/$${2}
      - traefik.http.middlewares.svodd-static-redirect.redirectRegex.permanent=true
      - traefik.http.routers.svodd-static.middlewares=cabinet-redirect

#      - traefik.enable=true
#      - traefik.docker.network=traefik-public
#      - traefik.http.routers.svodd-static.rule=Host(`static.localhost1`)
#      - traefik.http.routers.svodd-static.entryPoints=http
#      - traefik.http.services.svodd-static.loadBalancer.server.port=80

networks:
  traefik-public:
    external: true
